### ISSUE TITLE
kenlm class-based lm usage

### ISSUE THREAD

**Issue by oplatek** [kpu/kenlm#102]
Hi,

I noticed in the documentation that you explain that `Kneser-Ney` smoothing has problems with classed-based models.

Can you please advise me or hint to the documentation how to actually use kenlm for training class-based models and also use CB LMs for estimation?

My use-case:
I have in domain text corpus with abstracted classes such as:
`My phone number is DIGIT DIGIT DIGIT    DIGIT DIGIT DIGIT  DIGIT DIGIT DIGIT`

I want to model the probabilities on the abstracted corpora.
However, I want to use the probabilities and `expand` the abstracted classes to instances so the following sentence can be scored by the language model.

`My phone number is 7 7 7   6 6 6  6 6 6`

How does the expanded ngrams should be normalized?
Is there any tool for doing that?

If I naively expand the ngrams simply by replacing the class `DIGIT` with all the possibilities the model will not be normalized. 

How can I interpret the perplexity, use querying etc? What else may break?

On the other hand, I want to keep the probability of the abstracted ngrams for the expanded version because I want the sentence  `My phone number is 777 666 666` to have the probability of the abstracted version `My phone number DIGIT DIGIT DIGIT  DIGIT DIGIT DIGIT  DIGIT DIGIT DIGIT`, right?

Thank you for any help

**Comment by kpu** [comment]
You're probably fine with number classing.  The issue is really whether you have an appropriate number of singletons, doubletons, etc.  If there aren't any singleton unigrams, or a weird number of them, then modified Kneser-Ney's discounts have assumptions that no longer hold.  In extreme cases, this causes lmplz to throw an exception.  You can make up discounts with `--discount_fallback`
