### ISSUE TITLE
I just want to extract n-gram counts to a result txt

### ISSUE THREAD

**Issue by bojone** [kpu/kenlm#201]
just like
```
ngram-count -text train.txt -order 3 -write train.txt.count
```
in SRILM. How can I do it with kenlm?

I try
```
./count_ngrams -o 3 --write_vocab_list chars.txt <sample.txt >result.txt
```
But I do not know how to read result.txt (in python).

**Comment by kpu** [comment]
This rough edges program is intended to help distribute the n-gram counting process in `lmplz` but you can use it for just counting. The output format is binary but it's pretty simple.  The file is an array of fixed-size records:
Vocabulary ids as 4-byte integers.  Since you've selected order 3, there are 3 of them.
An 8-byte integer counter.  

So in this case each record is 3*4 + 8 = 20 bytes.  The records are sorted in suffix order (see the paper for an example).  
I think you can do something with struct.unpack in python.  Have fun.

**Comment by FredWe** [comment]
Then how can I read a count file (from count_ngrams) and finally estimate a lm ?
Is there any test to help this ?
