### ISSUE TITLE
kenlm temporary files problem

### ISSUE THREAD

**Issue by cmathx** [kpu/kenlm#211]
I used kenlm to train 5-gram model with 1TB data using cutoff. It will generate huge temporary files. But I didn't see these temporary files in my configure temporary directory. Where does these temporary files save?  Are the temporary files so so many?
As my remain disk space is not sufficient, I want to clean disk cache when running the lmplz training application. If I clean the disk cache to free disk space, does the lmplz train application work normally?

**Comment by kpu** [comment]
Temporary files are created by`lmplz` in the directory you specify using `-T`.  They are created using `mkstemp` then immediately `unlink`ed.  This has the good property that the operating system will clean up temporary files automatically in the event of a crash.  
You should check that the directory you specified is not something small like a RAM disk.  Often `/tmp` is a RAM disk.  
Cutoffs have little impact on peak disk usage during `lmplz` because the n-grams still have to be counted.  
I am not sure what is meant by cleaning the disk cache or how that would help anything.  But having more disk space would be useful.  
Temporary file compression has not been implemented but would probably help.  Would require a fair amount of coding.

**Comment by cmathx** [comment]
Thank you.

**Comment by cmathx** [comment]
I found if I train 5-gram with huge data(maybe 1TB), it cost much time in reading data. If I want to modify kenlm to read data in multi-thread mode,  is it difficult?
