### ISSUE TITLE
Continuous ngram count

### ISSUE THREAD

**Issue by francisr** [kpu/kenlm#58]
Is there a nice way to emulate SRILM's continuous-ngram-count? My goal is to have markers for punctuation (such as commas, periods, exaclamation marks, etc.) and to be able to keep context across sentences. 
Currently I put the whole text on one line, but it's not great memory wise.

**Comment by kpu** [comment]
I could optimize the reading in corpus_count.cc to stream through words instead of buffering a line.  Or add a command line option.

On June 4, 2016 12:15:02 AM GMT+01:00, "Rémi Francis" <notifications@github.com> wrote:
>Is there a nice way to emulate SRILM's continuous-ngram-count? My goal
>is to have markers for punctuation (such as commas, periods,
>exaclamation marks, etc.) and to be able to keep context across
>sentences. 
>Currently I put the whole text on one line, but it's not great memory
>wise. 
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/kpu/kenlm/issues/58

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by francisr** [comment]
A flag would be good, it would make it obvious that it's a possibility, and
you wouldn't have to manipulate your text beforehand.

**Comment by kpu** [comment]
In 3cf1d2f585d1b3a6c11c18e2688b64c93940c109 I've made it read one line at a time so memory is no longer an issue (at least in this tool).  Agree an option would be nice, would welcome a patch.

**Comment by francisr** [comment]
Thanks!
So I guess if I don't want to have counts for <s> and </s> I just have to remove:
    writer.StartSentence();
    writer.Append(end_sentence);
From the code you changed?

**Comment by kpu** [comment]
The beginning of sentence symbol `<s>` needs to be there as context for the first N-1 words.  It was never counted since it only appears as context.  However, it does count for purposes of being an extension to the left of a word in Kneser-Ney smoothing.  

The end of sentence symbol `</s>` is hard-coded into the vocabulary, but you don't have to actually use it.  

You could move `writer.BeginSentence()` out of the loop (so it happens only once, initializing the context for the first N-1 words).  And remove `writer.Append(end_sentence)' entirely.
