### ISSUE TITLE
LM without Probabilities including <s> <s/>

### ISSUE THREAD

**Issue by weidler** [kpu/kenlm#64]
Hi,

I am using the tool to build a LM over Entity Grids. As it is obvious i am therefore not interested in including probabilities of n-gramms that contain the sentence boundaries. Is it possible to somehow achieve this? I still want to only calculate n-gramms within a sentence so making one big sentence would not solve the problem.

thanks! (especially for the great tool!)

**Comment by kpu** [comment]
Can you formally specify what you want to happen at the beginning or end of sentence?  For line

A B C D E F

what n-grams are extracted?

**Comment by weidler** [comment]
So lets assume a corpus like this (lines are sentences):

A B C D E
F G H I J
K L M N O

then the 3-gramms would be:

ABC, BCD, CDE, FGH, GHI, HIJ, KLM, LMN, MNO

which means not including those 3-gramms:

<s>AB, DE</s>, <s>FG, IJ</s>, ...

Essentially i want to not include all n-gramms including <s> or </s>

thanks!

**Comment by kpu** [comment]
And if the input is "A B" then the output is nothing?  

This can be done by changing code around https://github.com/kpu/kenlm/blob/master/lm/builder/corpus_count.cc#L96 and https://github.com/kpu/kenlm/blob/master/lm/builder/corpus_count.cc#L252 to fill in the first few words instead of StartSentence.
