### ISSUE TITLE
Compute probabilities of all n-grams

### ISSUE THREAD

**Issue by sergey-serebryakov** [kpu/kenlm#70]
Hi Kenneth!
I am now using kenlm to experiment with different language models. From time to time I need to compute conditional probabilities of all n-grams. Arpa files do not contain them all and there is a rule how to compute probabilities that are not explicitly listed. I wrote a simple 20 line python script that uses arpa package to do that. Basically what that package (arpa) does is it accepts an n-gram string and returns probability of a last word conditioned on prefix. Maybe I did something wrong but it takes "forever" to compute, for instance, all 5-gram probabilities even with hundreds of threads.
I am wondering what would be the best way to compute probabilities of all possible n-grams with kenlm? I looked through the code and  your examples and I think something like this may work:

1. Convert arpa to binary (probing?).
2. Load that model.
3. Write OpenMP parallel loop and use FullScoreForgotState to get probabilities.

Does it sound like something reasonable or is there a better way to do it?

Thanks,
Sergey.

**Comment by kpu** [comment]
All vocabulary^5 5-grams?!  You'd be better off doing dynamic programming and explicitly exploiting the sparsity of the model.  

For example, the vast majority of p(w_5 | w_1^4) will result in p(w_5) * b(w_4) because w_4^5 and w_3^4 don't appear in the ARPA file.  Handle these in bulk, then treat the bigrams as exceptions.  But don't just do a full query for bigram exceptions.  In these cases, treat bigrams as the bulk rule and handle trigrams as exceptions.  Then handle trigrams that exist as the rule and handle 4-grams as exceptions...
