### ISSUE TITLE
Compilation Problem

### ISSUE THREAD

**Issue by usmanshahid** [kpu/kenlm#72]
I'm getting this error while trying to compile kenlm with make -j 4, please help.

 undefined reference to `boost::unit_test::ut_detail::normalize_test_case_name

**Comment by kpu** [comment]
Smells like you have a different version of Boost headers and libraries installed?

**Comment by usmanshahid** [comment]
Thanks for the response, my current boost version is
Version: 1.58.0.1ubuntu1
Do I need an older version?

**Comment by kpu** [comment]
The version number is fine.  But something about your Boost installation is broken.  Possibly because sometimes Boost changes based on compiler version.  

I suggest you write a quickie Boost program and get it to compile and link properly.  Perhaps this: http://www.boost.org/doc/libs/1_62_0/doc/html/program_options/tutorial.html .  Until that works, it's been you, Ubuntu, and Boost to solve.
